services:
  - type: web
    name: powai
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build:render
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
