services:
  - type: web
    name: powai
    env: node
    plan: free
    buildCommand: NPM_CONFIG_PRODUCTION=false npm install && npm run build:render
    startCommand: NODE_ENV=production npm run start
    healthCheckPath: /api/health
    envVars: []
