import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
        headline: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        body: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        label: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Inspiration specific colors
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#d3e4fe",
        "on-primary-container": "#475266",
        "error-dim": "#4e0309",
        "surface-container-high": "#e2e9ec",
        surface: "#f8f9fa",
        "on-tertiary-fixed": "#373851",
        "inverse-surface": "#0c0f10",
        "on-background": "#2b3437",
        "inverse-on-surface": "#9b9d9e",
        "tertiary-dim": "#51516c",
        "on-primary-fixed": "#354053",
        "on-secondary-fixed": "#314055",
        "surface-variant": "#dbe4e7",
        "secondary-fixed-dim": "#c5d6f0",
        "on-surface": "#2b3437",
        "surface-bright": "#f8f9fa",
        "on-tertiary-fixed-variant": "#54546f",
        "surface-dim": "#d1dce0",
        "error-container": "#fe8983",
        error: "#9f403d",
        "on-surface-variant": "#586064",
        "surface-tint": "#545f73",
        "inverse-primary": "#dae6fe",
        "tertiary-fixed-dim": "#cbc9e9",
        "secondary-dim": "#44546a",
        "primary-fixed": "#d8e3fb",
        "surface-container": "#eaeff1",
        "surface-container-low": "#f1f4f6",
        "on-tertiary": "#fbf7ff",
        "primary-dim": "#485367",
        "primary-container": "#d8e3fb",
        "on-secondary-container": "#435368",
        "on-primary-fixed-variant": "#515c70",
        "primary-fixed-dim": "#cad5ed",
        "tertiary-fixed": "#d9d7f8",
        "on-secondary-fixed-variant": "#4d5d73",
        "on-secondary": "#f7f9ff",
        "on-error-container": "#752121",
        "tertiary-container": "#d9d7f8",
        "outline-variant": "#abb3b7",
        "on-primary": "#f6f7ff",
        outline: "#737c7f",
        "on-tertiary-container": "#4a4a65",
        "on-error": "#fff7f6",
        tertiary: "#5d5d78",
        "surface-container-highest": "#dbe4e7",
        "secondary-fixed": "#d3e4fe",
        ivory: "#F8FAFC",
        vellum: "#F1F4F6",
        "slate-ink": "#1E293B",
        "slate-muted": "#64748B",
        "accent-midnight": "#1E293B",
        "powai-blue": "#1E293B",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "1rem",
        "2xl": "1.25rem",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        "card-hover": "var(--shadow-card-hover)",
        "soft-lg": "var(--shadow-lg)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0", opacity: "0" },
          to: { height: "var(--radix-accordion-content-height)", opacity: "1" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)", opacity: "1" },
          to: { height: "0", opacity: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-out": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(10px)" },
        },
        "scale-in": {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "slide-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "count-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "fade-out": "fade-out 0.3s ease-out",
        "scale-in": "scale-in 0.3s ease-out",
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "slide-up": "slide-up 0.6s ease-out forwards",
        "count-up": "count-up 0.4s ease-out forwards",
        enter: "fade-in 0.3s ease-out, scale-in 0.2s ease-out",
        exit: "fade-out 0.3s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
